export const CHANGE_COLOR = 'CHANGE_COLOR';

export const SCORE_BACKGROUND_COLOR_ID = 'SCORE_BACKGROUND_COLOR_ID';
export const SCORE_TEXT_COLOR_ID = 'SCORE_TEXT_COLOR_ID';
export const SCORE_PLAYER_COLOR_ID = 'SCORE_PLAYER_COLOR_ID';
export const SCORE_SLASH_COLOR_ID = 'SCORE_SLASH_COLOR_ID';
export const SCORE_TOTAL_COLOR_ID = 'SCORE_TOTAL_COLOR_ID';
